<a href="https://colab.research.google.com/github/gahz8212/python/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf

scalar = tf.constant(1)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                      [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(tf.rank(scalar))
print(tf.rank(vector))
print(tf.rank(matrix))
print(tf.rank(tensor))


tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [8]:
# =========================
# 0. 라이브러리 / 재현성 설정
# =========================
import numpy as np
import tensorflow as tf
np.random.seed(42)
tf.random.set_seed(42)
x=np.array([[0.0,0.0],
            [0.0,1.0],
            [1.0,0.0],
            [1.0,1.0]],dtype=np.float32)
y=np.array([[-1.0],[1.0],[1.0],[1.0]],dtype=np.float32)
n_input=2 #독립변수 갯수
n_output=1 #종속변수 갯수


In [9]:
perceptron = tf.keras.Sequential([
    tf.keras.layers.Dense(
        units=n_output,
        activation="tanh",       # 출력 범위: (-1, +1) -> y와 궁합이 좋음
        input_shape=(n_input,),  # (2,) 로 정확히 지정
        kernel_initializer="random_uniform",
        bias_initializer="zeros"
    )
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
perceptron.compile(
    loss="mse",
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    metrics=["mse"]
)

In [11]:
history=perceptron.fit(x,y,epochs=1000,verbose=2)

Epoch 1/1000
1/1 - 1s - 939ms/step - loss: 1.0016 - mse: 1.0016
Epoch 2/1000
1/1 - 0s - 126ms/step - loss: 0.7509 - mse: 0.7509
Epoch 3/1000
1/1 - 0s - 58ms/step - loss: 0.6409 - mse: 0.6409
Epoch 4/1000
1/1 - 0s - 141ms/step - loss: 0.5871 - mse: 0.5871
Epoch 5/1000
1/1 - 0s - 52ms/step - loss: 0.5546 - mse: 0.5546
Epoch 6/1000
1/1 - 0s - 52ms/step - loss: 0.5314 - mse: 0.5314
Epoch 7/1000
1/1 - 0s - 48ms/step - loss: 0.5126 - mse: 0.5126
Epoch 8/1000
1/1 - 0s - 50ms/step - loss: 0.4963 - mse: 0.4963
Epoch 9/1000
1/1 - 0s - 51ms/step - loss: 0.4816 - mse: 0.4816
Epoch 10/1000
1/1 - 0s - 31ms/step - loss: 0.4678 - mse: 0.4678
Epoch 11/1000
1/1 - 0s - 33ms/step - loss: 0.4547 - mse: 0.4547
Epoch 12/1000
1/1 - 0s - 31ms/step - loss: 0.4422 - mse: 0.4422
Epoch 13/1000
1/1 - 0s - 31ms/step - loss: 0.4302 - mse: 0.4302
Epoch 14/1000
1/1 - 0s - 32ms/step - loss: 0.4187 - mse: 0.4187
Epoch 15/1000
1/1 - 0s - 32ms/step - loss: 0.4075 - mse: 0.4075
Epoch 16/1000
1/1 - 0s - 34ms/step - loss: 0.3

In [16]:
# history.history['mse']
res=perceptron.predict(x,verbose=2)
print(res)

1/1 - 0s - 56ms/step
[[-0.8755607 ]
 [ 0.9224192 ]
 [ 0.92241913]
 [ 0.99978405]]


**np.where(res>=0,1.0,-1.0)**

* 손실함수
* 옵티마이저
* 활성화함수

# 텐서가 되어야 함.
## 2차원 텐서가 되어야 함.

```
import pytorch
```
[파이토치 참고사이트](https://pytorch.org)
<img src="https://pixabay.com/ko/images/download/monkey-24705.png" alt="monkey" width="200px"/>
🍎 🐒 📻

<table>
<tr>
<td>🍏</td>
<td>◀</td>
</tr>
</table>

In [18]:
import torch
import torch.nn as nn

# =========================
# 1. 재현성(옵션이지만 권장)
# =========================
torch.manual_seed(42)

# =========================
# 2. 데이터 (float32)
# =========================
x = torch.tensor([[0.0, 0.0],
                  [0.0, 1.0],
                  [1.0, 0.0],
                  [1.0, 1.0]], dtype=torch.float32)

y = torch.tensor([[-1.0],
                  [ 1.0],
                  [ 1.0],
                  [ 1.0]], dtype=torch.float32)

# =========================
# 3. 모델: Linear(2->1) + tanh
# =========================
model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Tanh()
)

# (TF 코드와 맞추려면 bias=0으로 시작하는 게 가장 유사)
with torch.no_grad():
    model[0].bias.zero_()

# =========================
# 4. 손실/옵티마이저
# =========================
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# =========================
# 5. 학습(epochs=500)
# =========================
for epoch in range(500):
    pred = model(x)                 # forward
    loss = criterion(pred, y)       # loss

    optimizer.zero_grad()           # grad 초기화
    loss.backward()                 # backward
    optimizer.step()                # update

In [19]:
# =========================
# 6. 예측
# =========================
with torch.no_grad():
    res = model(x)
    pred_class = torch.where(res >= 0, torch.tensor(1.0), torch.tensor(-1.0))

print("=== Raw prediction (tanh output) ===")
print(res)

print("\n=== Class prediction (-1 or +1) ===")
print(pred_class)

print("\n=== Ground truth (y) ===")
print(y)

# =========================
# 7. 학습된 파라미터 확인
# =========================
W = model[0].weight.data   # shape (1,2)
b = model[0].bias.data     # shape (1,)
print("\n=== Learned weights (W) and bias (b) ===")
print("W:\n", W)
print("b:\n", b)

# =========================
# 8. 부호 기준 정확도
# =========================
acc = (pred_class == y).float().mean().item()
print(f"\nSign-based accuracy: {acc*100:.2f}%")

=== Raw prediction (tanh output) ===
tensor([[-0.8196],
        [ 0.8884],
        [ 0.8884],
        [ 0.9993]])

=== Class prediction (-1 or +1) ===
tensor([[-1.],
        [ 1.],
        [ 1.],
        [ 1.]])

=== Ground truth (y) ===
tensor([[-1.],
        [ 1.],
        [ 1.],
        [ 1.]])

=== Learned weights (W) and bias (b) ===
W:
 tensor([[2.5699, 2.5699]])
b:
 tensor([-1.1557])

Sign-based accuracy: 100.00%


In [59]:
import torch
import torch.nn as nn

# 1) 재현성
torch.manual_seed(42)

# 2) 예시 데이터 (면적m^2 -> 집값)
#    실제로는 CSV에서 가져오면 되지만, "가장 간단" 버전이라 여기선 직접 만듦
x = torch.tensor(
                  [[30.0,1],
                  [40.0,2],
                  [50.0,2],
                  [60.0,3],
                  [70.0,3],
                  [80.0,4],


                  ], dtype=torch.float32)   # (N, 2) 이므로 2개의 입력 특성

y = torch.tensor([[260.0],
                  [390.0],
                  [450.0],
                  [580.0],
                  [650.0],
                  [780.0],
                  ], dtype=torch.float32)  # (N, 1)  (예: 단위=만원/백만원 등)

# 3) 모델: 선형회귀(2 -> 1) - x의 특성 수에 맞춰 2개의 입력 특성으로 변경
model = nn.Linear(2, 1)

# 4) 손실/옵티마이저
loss_fn = nn.MSELoss()
opt = torch.optim.SGD(model.parameters(), lr=0.0001)

# 5) 학습
for epoch in range(20000):
    pred = model(x)
    loss = loss_fn(pred, y)

    opt.zero_grad()

    loss.backward()
    opt.step()

# 6) 예측(새 면적에 대해 집값 예측)
with torch.no_grad():
    new_x1 = torch.tensor([[55.0,2]], dtype=torch.float32)  # 45m^2와 2개의 방
    new_pred1 = model(new_x1)
    new_x2 = torch.tensor([[75.0,4]], dtype=torch.float32)  # 45m^2와 2개의 방
    new_pred2 = model(new_x2)

# print("학습된 가중치(w), 바이어스(b):", model.weight, model.bias.item()) # .item()을 model.weight에서 제거
print("55m^2, 2개의 방 예측 집값:", new_pred1.item())
print("75m^2, 4개의 방 예측 집값:", new_pred2.item())

55m^2, 2개의 방 예측 집값: 510.9518127441406
75m^2, 4개의 방 예측 집값: 722.2432250976562
